#! /bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin
[ -f /etc/default/halt ] && . /etc/default/halt

. /lib/services/init-functions

do_stop()
{
	log_action_msg "System reboot now"
	reboot -d -f -i
}

case "$1" in
start)
	# no-op
	;;
restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 1
	;;
stop)
	do_stop
	;;
*)
	echo "Usage: $0 start|stop" >&2
	exit 1
	;;
esac
